# Generated by Django 5.2 on 2025-04-28 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='storageunit',
            name='total_units',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
