# Generated by Django 5.2 on 2025-04-28 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rooms', '0002_storageunit_total_units'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='contract_status',
            field=models.CharField(choices=[('active', 'Active'), ('terminated', 'Terminated'), ('renewed', 'Renewed')], default='active', max_length=20),
        ),
    ]
