# Generated by Django 5.2 on 2025-04-28 21:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_review_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storageunit',
            name='available',
        ),
        migrations.AddField(
            model_name='storageunit',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='storageunit',
            name='image',
            field=models.ImageField(blank=True, upload_to='storage_units/'),
        ),
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='review',
            name='storage_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.storageunit'),
        ),
        migrations.AlterField(
            model_name='storageunit',
            name='price_per_month',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='storageunit',
            name='size',
            field=models.CharField(max_length=100),
        ),
    ]
