# Generated by Django 5.2 on 2025-05-17 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_storageunit_available_storageunit_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='storage_unit',
        ),
        migrations.RemoveField(
            model_name='review',
            name='user',
        ),
        migrations.DeleteModel(
            name='StorageUnit',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
